version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "8081:8080"
    volumes:
     - .:/code
    environment:
      - WAIT_HOSTS=mongo:27017
      - NODE_ENV=development
    depends_on:
      - "mongo"
  mongo:
      container_name: mongo
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"
