# docker-compose.yml
app:
  build: ./
  volumes:
    - ./:/var/www/app
  ports:
    - 5000:5000
  environment:
    - NODE_ENV=development
    - PORT=5000
  command:
    sh -c 'npm i && node_modules/.bin/nodemon app.js --exec babel-node --'