version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8081:8080"
    volumes:
     - .:/code
    environment:
      - NODE_ENV=production
    depends_on:
      - "mongo"
  mongo:
      container_name: mongo
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"
